### ISSUE TITLE
Error when running in Windows or WSL

### ISSUE THREAD

**Issue by Gamer4Life2020** [prs-eth/RollingDepth#10]
E:\_3D-SBS_\RollingDepth>python run_video.py -i ./data/samples -o ./output/samples_fast -p fast --save-npy true --verbose

Traceback (most recent call last):
  File "E:\_3D-SBS_\RollingDepth\run_video.py", line 32, in <module>
    from rollingdepth import (
  File "E:\_3D-SBS_\RollingDepth\rollingdepth\__init__.py", line 22, in <module>
    from .rollingdepth_pipeline import RollingDepthOutput, RollingDepthPipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_3D-SBS_\RollingDepth\rollingdepth\rollingdepth_pipeline.py", line 32, in <module>
    from diffusers import (
ImportError: cannot import name 'AutoencoderKL' from 'diffusers' (unknown location)

----------------------------------------

E:\_3D-SBS_\RollingDepth>pip list
Package                Version
---------------------- ------------
antlr4-python3-runtime 4.9.3
certifi                2024.8.30
charset-normalizer     3.4.0
colorama               0.4.6
contourpy              1.3.1
cycler                 0.12.1
einops                 0.8.0
filelock               3.16.1
fonttools              4.55.1
fsspec                 2024.10.0
huggingface-hub        0.26.3
idna                   3.10
Jinja2                 3.1.4
kiwisolver             1.4.7
MarkupSafe             3.0.2
matplotlib             3.9.3
mpmath                 1.3.0
networkx               3.4.2
numpy                  2.1.3
omegaconf              2.3.0
packaging              24.2
pillow                 11.0.0
pip                    22.3
pyav                   14.0.0
pyparsing              3.2.0
python-dateutil        2.9.0.post0
PyYAML                 6.0.2
regex                  2024.11.6
requests               2.32.3
safetensors            0.4.5
setuptools             65.5.0
six                    1.17.0
sympy                  1.13.3
tokenizers             0.20.3
torch                  2.4.1
torchvision            0.19.1
tqdm                   4.67.1
transformers           4.46.3
typing_extensions      4.12.2
urllib3                2.2.3
xformers               0.0.28.post1

**Comment by Gamer4Life2020** [comment]
Didn't have diffusers installed as DepthCrafter was having same issue.
