### ISSUE TITLE
Issues trying to run not sure if pytorch or xformers

### ISSUE THREAD

**Issue by Gamer4Life2020** [prs-eth/RollingDepth#12]
(venv) E:\_RollingDepth_>python run_video.py -i data/samples -o output/samples_fast -p fast --save-npy true --verbose
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu118 with CUDA 1108 (you have 2.5.1+cu118)
    Python  3.12.4 (you have 3.12.3)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "E:\_RollingDepth_\venv\Lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
    ^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'triton'
INFO:root:Using preset: fast
INFO:root:arguments: {'res': 768, 'snippet_lengths': [3], 'cap_dilation': True, 'dtype': 'fp16', 'refine_snippet_len': 3, 'refine_start_dilation': 6, 'dilations': [1, 25], 'refine_step': 0, 'input_video': 'data/samples', 'output_dir': 'output/samples_fast', 'preset': 'fast', 'start_frame': 0, 'frame_count': 0, 'checkpoint': 'prs-eth/rollingdepth-v1-0', 'max_vae_bs': 4, 'output_fps': 0, 'restore_res': False, 'save_sbs': True, 'save_npy': True, 'save_snippets': False, 'color_maps': ['Spectral_r', 'Greys_r'], 'resample_method': 'BILINEAR', 'unload_snippet': False, 'verbose': True, 'seed': None}
INFO:root:device = cuda
INFO:root:Found 5 videos.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  6.02it/s]
Traceback (most recent call last):
  File "E:\_RollingDepth_\run_video.py", line 468, in <module>
    pipe.enable_xformers_memory_efficient_attention()
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1606, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1632, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1622, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 226, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 219, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 226, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 219, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\attention_processor.py", line 342, in set_use_memory_efficient_attention_xformers
    raise e
  File "E:\_RollingDepth_\venv\Lib\site-packages\diffusers\models\attention_processor.py", line 336, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\xformers\ops\fmha\__init__.py", line 276, in memory_efficient_attention
    return _memory_efficient_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\xformers\ops\fmha\__init__.py", line 395, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\xformers\ops\fmha\__init__.py", line 414, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 119, in _dispatch_fw
    return _run_priority_list(
           ^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 55, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    xFormers wasn't build with CUDA support
    attn_bias type is <class 'NoneType'>
    operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    operator wasn't built - see `python -m xformers.info` for more info
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40

(venv) E:\_RollingDepth_>
-------------------------------------------------------------------------------
I have tried all the ones from https://github.com/facebookresearch/xformers and have tried different pytorch(s) from https://pytorch.org/ and they are always incompatible for some reason. Currently using DepthCrafter but really want to try this out.

**Comment by markkua** [comment]
Hi, have you tried running without xformers?

**Comment by Gamer4Life2020** [comment]
I uninstalled xformers and it starts to run but then errors:

Successfully uninstalled xformers-0.0.27.post2+cu118

(venv) E:\_RollingDepth_>python run_video.py -i data/samples -o output/samples_fast -p fast --save-npy true --verbose
INFO:root:Using preset: fast
INFO:root:arguments: {'res': 768, 'snippet_lengths': [3], 'cap_dilation': True, 'dtype': 'fp16', 'refine_snippet_len': 3, 'refine_start_dilation': 6, 'dilations': [1, 25], 'refine_step': 0, 'input_video': 'data/samples', 'output_dir': 'output/samples_fast', 'preset': 'fast', 'start_frame': 0, 'frame_count': 0, 'checkpoint': 'prs-eth/rollingdepth-v1-0', 'max_vae_bs': 4, 'output_fps': 0, 'restore_res': False, 'save_sbs': True, 'save_npy': True, 'save_snippets': False, 'color_maps': ['Spectral_r', 'Greys_r'], 'resample_method': 'BILINEAR', 'unload_snippet': False, 'verbose': True, 'seed': None}
INFO:root:device = cuda
INFO:root:Found 5 videos.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.42it/s]
WARNING:root:Run without xformers
Processing videos:   0%|                INFO:root:241 frames loaded from video data\samples\1_gokart_cropped.mp4 ?it/s]
Processing videos:   0%|                                                                         | 0/5 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "E:\_RollingDepth_\run_video.py", line 490, in <module>
    pipe_out: RollingDepthOutput = pipe(
                                   ^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\rollingdepth\rollingdepth_pipeline.py", line 135, in __call__
    pipe_output = self.forward(
                  ^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\rollingdepth\rollingdepth_pipeline.py", line 291, in forward
    snippet_pred_ls = self.init_snippet_infer(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\rollingdepth\rollingdepth_pipeline.py", line 436, in init_snippet_infer
    noise_pred = self.single_step(
                 ^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\rollingdepth\rollingdepth_pipeline.py", line 651, in single_step
    noise_pred = self.unet(
                 ^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_RollingDepth_\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UNet2DConditionModel.forward() got an unexpected keyword argument 'num_view'

(venv) E:\_RollingDepth_>

**Comment by Gamer4Life2020** [comment]
Ok thanks, I'll redo it again and try to keep everything virtualized if not I'll try linux and see how far I can get.
